services:
  db:
    image: mysql:latest
    container_name: slot_engine_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slot_game
      MYSQL_USER: slot_user
      MYSQL_PASSWORD: slot_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: