package com.igt.spincoreengine.api.model.response;

import com.igt.spincoreengine.model.WinningLine;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

@Schema(description = "Response containing the result of a spin")
public class SpinResponse implements Serializable {

    @Schema(description = "3x5 matrix of symbols generated by the spin (3 rows, 5 reels)", example = "[[\"A\",\"K\",\"Q\",\"A\",\"K\"],[\"K\",\"W\",\"A\",\"K\",\"Q\"],[\"Q\",\"A\",\"K\",\"Q\",\"A\"]]")
    private List<List<String>> matrix;
    @Schema(description = "List of paylines that resulted in a win")
    private List<WinningLine> winningLines;
    @Schema(description = "Total win amount for this spin (sum of all winning paylines)", example = "10.00")
    private BigDecimal totalWin;
    @Schema(description = "Player's updated balance after the spin", example = "105.00")
    private BigDecimal newBalance;

    public SpinResponse() {
    }

    public SpinResponse(List<List<String>> matrix, List<WinningLine> winningLines, BigDecimal totalWin, BigDecimal newBalance) {
        this.matrix = matrix;
        this.winningLines = winningLines;
        this.totalWin = totalWin;
        this.newBalance = newBalance;
    }

    public List<List<String>> getMatrix() {
        return matrix;
    }

    public void setMatrix(List<List<String>> matrix) {
        this.matrix = matrix;
    }

    public List<WinningLine> getWinningLines() {
        return winningLines;
    }

    public void setWinningLines(List<WinningLine> winningLines) {
        this.winningLines = winningLines;
    }

    public BigDecimal getTotalWin() {
        return totalWin;
    }

    public void setTotalWin(BigDecimal totalWin) {
        this.totalWin = totalWin;
    }

    public BigDecimal getNewBalance() {
        return newBalance;
    }

    public void setNewBalance(BigDecimal newBalance) {
        this.newBalance = newBalance;
    }

    @Override
    public String toString() {
        return "SpinResponse{" +
                "matrix=" + matrix +
                ", winningLines=" + winningLines +
                ", totalWin=" + totalWin +
                ", newBalance=" + newBalance +
                '}';
    }
}
